### PR TITLE
fix(export): prevent export progress from freezing at 102%

### LINKED ISSUE #228: Rendering never finishes for 13-minute video (frozen at 102%)
### Description

Shareable link not generated for a 13-minute video, but the percentage reaches 102% before freezing.
Local export not finished for a 13-minute video, endless "Rendering..." stage.

### Reproduction

1. Update Cap to 0.3.10
2. Record a 13-minute video on Free plan
3. Attempt to export the video (incorrect timestamp of 1:23 showed, vs. the actual 13:09 length)
4. When progress bar turns to "Rendering" bar, wait for several minutes
5. Upgrade to Pro plan (monthly) to try to circumvent this issue (assumed the export might be frozen due to processing power?)
6. Attempt to restart the export using the "Reload" option in Cap's "export in progress" UI
7. Choose "Create Shareable Link" instead
8. Once "Rendering - 102% hits, wait several minutes

## Result

Nothing happens, export is frozen at the Rendering stage.

Screenshot 2024-12-26 at 12 53 23 PM

### Additional Context

Screenshot 2024-12-26 at 12 48 56 PM

Screenshot 2024-12-26 at 12 55 22 PM

### No Debug Logs Found

Screenshot 2024-12-26 at 12 57 03 PM

### PR DESCRIPTION
**Pull request by onyedikachi-david**
## Description
This PR fixes issue #228 where video export progress gets stuck at 102% for longer videos. The fix addresses both the backend frame calculation and frontend progress handling.

/claim #228 

### Fixes
Closes #228

### CODE REVIEW

File: apps/desktop/src/routes/editor/Header.tsx [hunk 1]
```diff
@@ -260,14 +260,26 @@ function ExportButton() {
       const progress = new Channel<RenderProgress>();
       progress.onmessage = (p) => {
         if (p.type === "FrameRendered" && progressState.type === "saving") {
-          const percentComplete = Math.round(
-            (p.current_frame / (progressState.totalFrames || 1)) * 100
+          const percentComplete = Math.min(
+            Math.round(
+              (p.current_frame / (progressState.totalFrames || 1)) * 100
+            ),
+            100
```
Comment (steven-the-qa) [inline apps/desktop/src/routes/editor/Header.tsx:268]: Why do we use 'Math.min' here?

**Review by steven-the-qa — COMMENTED** [review]
I don't see anything alarming, but I'll let one of the maintainers approve. I can do a quick QA review when I get home a few hours.

File: apps/desktop/src/routes/editor/Header.tsx (hunk 1 above)
Comment (onyedikachi-david) [reply apps/desktop/src/routes/editor/Header.tsx:268]: so it will not exceed 100%

**Comment by steven-the-qa** [comment]
I don't see anything alarming, but I'll let one of the maintainers approve. I can do a quick QA review when I get home a few hours.

**Comment by steven-the-qa** [comment]
I can confirm the build on this branch is successfully exporting the videos, but the UI still shows the wrong % when the export completes.

I also wasn't able to create an exported mp4 using the `.cap` file from the recording I originally had problems with. I've attached evidence here: https://drive.google.com/drive/folders/1CbylevoffsDtLUckU7ssmvN6g8qXfrk7?usp=sharing cc: @richiemcilroy

**Comment by onyedikachi-david** [comment]
https://github.com/user-attachments/assets/0a2c3f57-f95b-4854-9fa6-361288b1716f

**Comment by steven-the-qa** [comment]
> https://github.com/user-attachments/assets/0a2c3f57-f95b-4854-9fa6-361288b1716f
> 
> 
> 
> @steven-the-qa Thanks for the review, i just implemented a fix addressing your observations.

Not sure what's going on on my machine, but I don't see the original .cap file exporting successfully. I see the same behavior. I didn't check behavior of new recordings. It seems you may have done that, though.

**Comment by onyedikachi-david** [comment]
That's weird.

**Comment by steven-the-qa** [comment]
> That's weird. Could you clarify what you mean by "original .cap files"

https://drive.google.com/drive/folders/1CbylevoffsDtLUckU7ssmvN6g8qXfrk7?usp=drive_link here are the 2 `.cap` files I had trouble exporting, from when I originally reported the bug.

Also, I noticed something odd about the `.cap` contents. The `display.mp4` is much shorter than the `audio-input.mp3` and `camera.mp4` files, and when I saw an incorrect video timestamp on that post-recording tiny window, it matched the timestamp of the `display.mp4`. The real issue might be that the `display.mp4` stopped recording too early.

**Comment by onyedikachi-david** [comment]
About the storage Issue (My Rust projects are just taking up storage space on my laptop 😄 ). I noticed an issue while testing: twice during recording sessions that showed as 5 minutes long in the UI tray, the editor only displayed 48 seconds of content when opened. Upon checking the logs, I found:

```
@cap/desktop:dev: Waiting for play signal...
@cap/desktop:dev: Starting pipeline execution
@cap/desktop:dev: Sending signal Play to screen_capture
@cap/desktop:dev: Screen recording started.
@cap/desktop:dev: Screen capture error occurred.
@cap/desktop:dev: Capture error: receiving on a closed channel
@cap/desktop:dev: Shutting down screen capture source thread.
@cap/desktop:dev: Received last screen frame. Finishing up encoding.
@cap/desktop:dev: Shutting down screen video encoding thread
@cap/desktop:dev: Shutting down pipeline execution
@cap/desktop:dev: Sending signal Shutdown to screen_capture
@cap/desktop:dev: screen_capture is unreachable!
@cap/desktop:dev: Pipeline has been stopped.
```

It appears the recording stopped prematurely (possibly due to storage issues or other constraints), but this failure isn't being communicated to the UI, which continues to show the recording as active.

**Comment by steven-the-qa** [comment]
> twice during recording sessions that showed as 5 minutes long in the UI tray, the editor only displayed 48 seconds of content when opened. Upon checking the logs, I found:

That's exactly what I saw!

**Comment by richiemcilroy** [comment]
Hey @onyedikachi-david, I've just pushed up a bunch of fixes/changes.

Going to decrease the bounty to $100, but still award it.

Took a while for me to get this done 😄

**Comment by onyedikachi-david** [comment]
Hi @richiemcilroy please remember to reward this and the other PR. Thank you sir.
